# filename: poem.py
print("Once upon a midnight dreary, while I pondered, weak and weary,")
print("Over many a quaint and curious volume of forgotten lore—")
print("When the nights were long and cold, and the days were short and old,")
print("And the fire burned low and the wind blew cold,")
print("I sat by the fireside,")
print("And dreamed of days gone by,")
print("And of all the things that I had seen and done,")
print("And of all the people that I had met,")
print("And of all the places that I had been.")
print("And as I sat there by the fireside,")
print("I heard a knock at the door,")
print("And I opened it,")
print("And there stood a man,")
print("A tall, dark man,")
print("With a long, black coat,")
print("And a wide-brimmed hat.")
print("And he said,")
print("“I am the Raven,”")
print("And I have come to take you away.")
print("And I said,")
print("“I will not go with you,”")
print("“I am not afraid of you.”")
print("But the Raven said,")
print("“You will come with me,”")
print("“And I will take you to a place where you will never see the light of day again.”")
print("And I said,")
print("“I will not go with you,”")
print("“I am not afraid of you.”")
print("But the Raven said,")
print("“You will come with me,”")
print("“And I will take you to a place where you will never see the light of day again.”")
print("And I said,")
print("“I will not go with you,”")
print("“I am not afraid of you.”")
print("But the Raven said,")
print("“You will come with me,”")
print("“And I will take you to a place where you will never see the light of day again.”")
print("And I said,")
print("“I will not go with you,”")
print("“I am not afraid of you.”")
print("But the Raven said,")
print("“You will come with me,”")
print("“And I will take you to a place where you will never see the light of day again.”")
print("And I said,")
print("“I will not go with you,”")
print("“I am not afraid of you.”")
print("But the Raven said,")
print("“You will come with me,”")
print("“And I will take you to a place where you will never see the light of day again.”")
print("And I said,")
print("“I will not go with you,”")
print("“I am not afraid of you.”")
print("But the Raven said,")
print("“You will come with me,”")
print("“And I will take you to a place where you will never see the light of day again.”")
print("And I said,")
print("“I will not go with you,”")
print("“I am not afraid of you.”")
print("But the Raven said,")
print("“You will come with me,”")
print("“And I will take you to a place where you will never see the light of day again.”")
print("And I said,")
print("“I will not go with you,”")
print("“I am not afraid of you.”")
print("But the Raven said,")
print("“You will come with me,”")
print("“And I will take you to a place where you will never see the light of day again.”")
print("And I said,")
print("“I will not go with you,”")
print("“I am not afraid of you.”")
print("But the Raven said,")
print("“You will come with me,”")
print("“And I will take you to a place where you will never see the light of day again.”")
print("And I said,")
print("“I will not go with you,”")
print("“I am not afraid of you.”")
print("But the Raven said,")
print("“You will come with me,”")
print("“And I will take you to a place where you will never see the light of day again.”")
print("And I said,")
print("“I will not go with you,”")
print("“I am not afraid of you.”")
print("But the Raven said,")
print("“You will come with me,”")
print("“And I will take you to a place where you will never see the light of day again.”")
print("And I said,")
print("“I will not go with you,”")
print("“I am not afraid of you.”")
print("But the Raven said,")
print("“You will come with me,”")
print("“And I will take you to a place where you will never see the light of day again.”")
print("And I said,")
print("“I will not go with you,”")
print("“I am not afraid of you.”")
print("But the Raven said,")
print("“You will come with me,”")
print("“And I will take you to a place where you will never see the light of day again.”")
print("And I said,")
print("“I will not go with you,”")
print("“I am not afraid of you.”")
print("But the Raven said,")
print("“You will come with me,”")
print("“And I will take you to a place where you will never see the light of day again.”")
print("And I said,")
print("“I will not go with you,”")
print("“I am not afraid of you.”")
print("But the Raven said,")
print("“You will come with me,”")
print("“And I will take you to a place where you will never see the light of day again.”")
print("And I said,")
print("“I will not go with you,”")
print("“I am not afraid of you.”")
print("But the Raven said,")
print("“You will come with me,”")
print("“And I will take you to a place where you will never see the light of day again.”")
print("And I said,")
print("“I will not go with you,”")
print("“I am not afraid of you.”")
print("But the Raven said,")
print("“You will come with me,”")
print("“And I will take you to a place where you will never see the light of day again.”")
print("And I said,")
print("“I will not go with you,”")
print("“I am not afraid of you.”")
print("But the Raven said,")
print("“You will come with me,”")
print("“And I will take you to a place where you will never see the light of day again.”")
print("And I said,")
print("“I will not go with you,”")
print("“I am not afraid of you.”")
print("But the Raven said,")
print("“You will come with me,”")
print("“And I will take you to a place where you will never see the light of day again.”")